using MasterDevs.ChromeDevTools.Protocol;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace MasterDevs.ChromeDevTools.Protocol.Chrome.Version13.Network
{
	/// <summary>
	/// Enables tracking for the Reporting API, events generated by the Reporting API will now be delivered to the client.
	/// Enabling triggers 'reportingApiReportAdded' for all existing reports.
	/// </summary>

	[SupportedBy("Chrome")]
	public class EnableReportingApiCommand: ICommand<EnableReportingApiCommandResult>
	{
		public string MethodName { get; } = ProtocolName.Network.EnableReportingApi;
		/// <summary>
		/// Whether to enable or disable events for the Reporting API
		/// </summary>
		public bool Enable { get; set; }
	}
}
